### ISSUE TITLE
Portfolio deployment

### ISSUE THREAD

**Issue by popey17** [popey17/Leo-Portfolio#7]
## This is the link to the GitHub page
https://popey17.github.io/Leo-Portfolio/

**Comment by AdnanOlarmmi** [comment]
Hi @popey17,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- Nice one deploying with GitHub pages.
- Nice one Updating your README file with the live version.
- Professional README.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by popey17** [comment]
@AdnanOlarmmi  Hi thanks for the review. Link to the site is already included in the readme file from the start. You can see in the live demo section of the readme file.
